sudo: required
language: node_js
node_js:
  - node
  - 12
  - 11
  - 10
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
before_script:
  - webdriver-manager clean
  - webdriver-manager update --versions.chrome=78.0.3904.70
script:
  - npm run test-travis
