language: node_js
os:
  - linux
  - osx
  - windows
dist: focal
osx_image: xcode12.5
node_js:
  - 16
  - 14
  - 12
addons:
  chrome: stable
services:
  - xvfb
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - export DISPLAY=':99.0'
  - npm set progress=false
  - npm install
before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$TRAVIS_NODE_VERSION" = "16" ]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter && ./cc-test-reporter before-build ; fi
script:
  - npm run prettier-check
  - npm run lint
  - npm run ng-lint
  - npm run build:dev
  - npm run unit-tests
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then npm run system-tests:windows ; else npm run system-tests ; fi
  # - npm run electron:build
after_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$TRAVIS_NODE_VERSION" = "16" ]; then ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT ; fi
